#ifndef __OCTEMU_H__
#define __OCTEMU_H__

#include "SDL3/SDL.h"

#ifndef OCTEMU_TICKRATE_CHIP8
#define OCTEMU_TICKRATE_CHIP8 15
#endif
#ifndef OCTEMU_TICKRATE_SCHIP
#define OCTEMU_TICKRATE_SCHIP 200
#endif
#ifndef OCTEMU_FOREGROUND_RGB
#define OCTEMU_FOREGROUND_RGB 0x2AA198
#endif
#ifndef OCTEMU_BACKGROUND_RGB
#define OCTEMU_BACKGROUND_RGB 0x002B36
#endif
#ifndef OCTEMU_WINDOW_WIDTH
#define OCTEMU_WINDOW_WIDTH 640
#endif
#ifndef OCTEMU_WINDOW_HEIGHT
#define OCTEMU_WINDOW_HEIGHT 320
#endif
#ifndef OCTEMU_VERSION
#define OCTEMU_VERSION "dev"
#endif

static const SDL_Scancode keymapping[16] = {
    SDL_SCANCODE_1, SDL_SCANCODE_2, SDL_SCANCODE_3, SDL_SCANCODE_4,
    SDL_SCANCODE_Q, SDL_SCANCODE_W, SDL_SCANCODE_E, SDL_SCANCODE_R,
    SDL_SCANCODE_A, SDL_SCANCODE_S, SDL_SCANCODE_D, SDL_SCANCODE_F,
    SDL_SCANCODE_Z, SDL_SCANCODE_X, SDL_SCANCODE_C, SDL_SCANCODE_V
};

#endif // __OCTEMU_H__
